export default [
  {
    id: 1,
    name: "Daniel Orion",
    location: "Kings Lodge, 27 Ikachi Str.",
    category: "Shopping",
    status: "Ongoing",
    errandItems: [
      {
        id: 1,
        name: "Kemps Cream Crackers",
        quantity: 2,
        price: 100,
      },
      {
        id: 2,
        name: "Gala Sausage Roll",
        quantity: 1,
        price: 100,
      },
      {
        id: 3,
        name: "Mirinda Soft Drink",
        quantity: 2,
        price: 600,
      },
    ],
    totalPrice: 800,
    rider: "Ifechi Samson",
  },
  {
    id: 2,
    name: "Amaka Okechukwu",
    location: "Queens Lodge, 27 Ikachi Str.",
    category: "Meal",
    status: "Received",
    errandItems: [
      {
        id: 1,
        name: "Rice and Stew",
        price: 300,
      },
      {
        id: 2,
        name: "Beans",
        price: 200,
      },
      {
        id: 3,
        name: "Beef",
        price: 150,
      },
      {
        id: 4,
        name: "Pasta",
        price: 200,
      },
    ],
    totalPrice: 850,
    rider: "Ifechi Samson",
  },
  {
    id: 3,
    name: "Kelechi Igbokwe",
    location: "Prince Lodge, 27 Ikachi Str.",
    category: "Laundry",
    status: "Ongoing",
    errandItems: [
      {
        id: 1,
        category: "Dry Cleaning",
        number: 2,
      },
      {
        id: 2,
        category: "Washing & Ironing",
        number: 3,
      },
    ],
    totalPrice: 1000,
    rider: "Ifechi Samson",
  },
  {
    id: 4,
    name: "Kingsley StupidBoy",
    location: "Boys Lodge, 27 Ikachi Str.",
    category: "Parcel",
    status: "Received",
    recipientName: "Justine Happiness",
    recipientAddress: "Somewhere Lodge, 27 Ikachi Str.",
    recipientNumber: "07054500125",
    rider: "Ifechi Samson",
  },
  {
    id: 5,
    name: "Daniel Orion",
    location: "Kings Lodge, 27 Ikachi Str.",
    category: "Shopping",
    status: "Received",
    errandItems: [
      {
        id: 1,
        name: "Kemps Cream Crackers",
        quantity: 2,
        price: 100,
      },
      {
        id: 2,
        name: "Gala Sausage Roll",
        quantity: 1,
        price: 100,
      },
      {
        id: 3,
        name: "Mirinda Soft Drink",
        quantity: 2,
        price: 600,
      },
    ],
    totalPrice: 800,
    rider: "Ifechi Samson",
  },
  {
    id: 6,
    name: "Amaka Okechukwu",
    location: "Queens Lodge, 27 Ikachi Str.",
    category: "Meal",
    status: "Received",
    errandItems: [
      {
        id: 1,
        name: "Rice and Stew",
        price: 300,
      },
      {
        id: 2,
        name: "Beans",
        price: 200,
      },
      {
        id: 3,
        name: "Beef",
        price: 150,
      },
      {
        id: 4,
        name: "Pasta",
        price: 200,
      },
    ],
    totalPrice: 850,
    rider: "Ifechi Samson",
  },
];
